#!/usr/bin/env bash
#Add a component into the header

apt update -y
apt install nginx -y
sed -i "/listen \[::\]:80 default_server;/a \\\n\tadd_header X-Served-By \"$(hostname)\";" /etc/nginx/sites-available/default
service nginx restart
