#!/usr/bin/env bash
#Add a component into the header

apt-get update
apt-get install -y nginx
HOSTNAME=$(cat /etc/hostname)
sed -i "/listen \[::\]:80 default_server;/a \\\n\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-enabled/default
service nginx restart
