#!/usr/bin/env bash
#Install a proxy on the load balancer

apt update -y
apt install haproxy=1.6.\* -y

echo "ENABLED=1" >> /etc/default/haproxy

echo "frontend http
    mode http
    bind :80
    default_backend web_backend

backend web-backend
    balance roundrobin
    server 3270-web-01 34.148.245.248 check
    server 3272-web-02 34.138.44.159 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
